server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: Manthan1121
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

#===JWT
security:
  jwt:
    secret-key: 9b49cc7622a06c36b3984d9483fc2766aa58d18fac147ff07f2783b0b5cc1e67
    expiration-time: 604800000
