server:
  port: 8081
  
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
  application:
    name: gateway-service

